/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * description des utilisateur
 */
export interface UserDocType {
  IdUser?: string;
  userName: string;
  password: string;
  [k: string]: unknown;
}
