// THIS FEATURE-FLAG FILE IS AUTOGENERATED,
//  REMOVAL OR CHANGES WILL CAUSE RELATED TYPES TO STOP WORKING
import 'quasar/dist/types/feature-flag';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import TWoMDatabase from 'app/src-electron/dataBase/database.type';
import { BrowserWindow } from 'electron';

declare module 'quasar/dist/types/feature-flag' {
  interface QuasarFeatureFlags {
    electron: true;
  }
}

declare global {
  namespace NodeJS {
    interface Global {
      __: NodeRequire;
      db: TWoMDatabase;
      win: BrowserWindow;
    }
  }
}
