// THIS FEATURE-FLAG FILE IS AUTOGENERATED,
//  REMOVAL OR CHANGES WILL CAUSE RELATED TYPES TO STOP WORKING
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { BrowserWindow } from 'electron';

declare module 'quasar/dist/types/feature-flag' {
  interface QuasarFeatureFlags {
    electron: true;
  }
}

declare global {
  namespace NodeJS {
    interface Global {
      __statics: string;
    }
  }
}
